//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_MegaCasting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public long Identifiant { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Siret { get; set; }
        public string Libelle { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Partenaire Partenaire { get; set; }
    }
}
