//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_MegaCasting_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Partenaire = new HashSet<Partenaire>();
        }
    
        public long Identifiant { get; set; }
        public string Intitule { get; set; }
        public Nullable<System.DateTime> Date_Debut_Publication { get; set; }
        public Nullable<int> Duree_Diffusion { get; set; }
        public Nullable<System.DateTime> Date_Debut_Contrat { get; set; }
        public Nullable<int> Nombre_Poste { get; set; }
        public string Localisation { get; set; }
        public string Description_Poste { get; set; }
        public string Description_Profil { get; set; }
        public string Metier { get; set; }
        public string Type_Contrat { get; set; }
        public string Domaine_metier { get; set; }
        public Nullable<long> Client { get; set; }
    
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partenaire> Partenaire { get; set; }
    }
}
