//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_MegaCastingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liste_Referentiel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liste_Referentiel()
        {
            this.Offre = new HashSet<Offre>();
        }
    
        public long Identifiant { get; set; }
        public string Type_Contrat { get; set; }
        public string Domaine_Metier { get; set; }
        public Nullable<long> Metier { get; set; }
    
        public virtual Metier Metier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre> Offre { get; set; }
    }
}
